apiVersion: v1
kind: Pod
metadata:
  name: nginxmx-pod1
  labels:
    team: integration
    app: todo
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
